FriendsOfAkeneo/CustomEntityBundle

AttributeType/CustomOptionMultiSelectType.php, AttributeType/CustomOptionSimpleSelectType.php
Fixed options displayed in attribute form values tab
=> Fixed attribute form values tab

README.md, Resources/doc/abstract_entities_and_repositories.rst, Resources/doc/crud_interface.rst
Updated README.md, abstract_entities_and_repositories.rst and Resources/doc/crud_interface.rst
=> Updated documentation

composer.json
Reverts akeneo-labs/CustomEntityBundle#56
=> Revert "UPDATE 1.5 changes composer require"

Entity/AbstractCustomOptionTranslation.php, Entity/AbstractTranslatableCustomEntity.php, MassEditConnector/Reader/ReferenceDataReader.php, Resources/doc/abstract_entities_and_repositories.rst, Versioning/VersionableInterface.php, composer.json, spec/Pim/Bundle/CustomEntityBundle/Action/QuickExportActionSpec.php
Upgrade the bundle for the 1.5 PIM
=> Upgrade-1.5

Configuration/Registry.php
Needed for the CustomEntityConnectorBundle
=> Added method to get configuration list

Entity/TranslatableTrait.php, Entity/TranslationTrait.php, Resources/config/savers.yml, Updater/Updater.php
Add translatable and translation traits to avoid copy/paste each time we need to add translation entities.
This PR also adds the possibility for a translated entity to handle translated properties and linked entities
=> Improve translation

Connector/Processor/Denormalization/ReferenceDataProcessor.php, Updater/Updater.php
- Improve thrown errors on the processor
- Manage many to one relation in a better way
=> Improve generic import of reference datas

Entity/AbstractCustomEntity.php
which most of the time is a lowercase version of the Class name
=> Define a default CustomEntityName

README.md
=> Update broken links for docs

docs/examples/CustomBundle/Resources/config/datagrid/fabric.yml
Aesthetic change on Fabric list
=> Change label

CHANGELOG-2.1.md, Entity/AbstractTranslatableCustomEntity.php, spec/Pim/Bundle/CustomEntityBundle/Entity/TranslatableCustomEntitySpec.php
=> GITHUB-130: Nullable type for getTranslation

Checker/ProductLinkChecker.php
=> Enable deleting entities with multiple reference data types

Action/Rest/CreateAction.php, Action/Rest/UpdateAction.php, Resources/config/actions.yml
=> Display validation error messages

CHANGELOG-2.1.md, Normalizer/CustomEntityNormalizer.php, Resources/config/requirejs.yml, Resources/public/js/controller/custom_entity-edit.js, Resources/public/js/field/custom-entity-select.js, Resources/public/js/form/common/edit-form.js, docs/examples/CustomBundle/Resources/config/form_extensions/brand/edit.yml, docs/examples/CustomBundle/Resources/config/form_extensions/color/edit.yml, docs/examples/CustomBundle/Resources/config/form_extensions/fabric/create.yml, docs/examples/CustomBundle/Resources/config/form_extensions/fabric/edit.yml, docs/examples/CustomBundle/Resources/config/form_extensions/pictogram/edit.yml, docs/examples/CustomBundle/Resources/config/validation.yml, spec/Pim/Bundle/CustomEntityBundle/Normalizer/CustomEntityNormalizerSpec.php
Fixes #138 and updates the example bundle
=> Fix incorrect form data after submitting an edit-form

Action/Rest/CreateAction.php, Action/Rest/UpdateAction.php, CHANGELOG-2.0.md, Normalizer/CustomEntityNormalizer.php, Resources/config/actions.yml, Resources/config/form_extensions_ee/reference_data_csv_permissions.yml, Resources/config/requirejs.yml, Resources/public/js/controller/custom_entity-edit.js, Resources/public/js/field/custom-entity-select.js, Resources/public/js/form/common/edit-form.js, Resources/translations/jsmessages.en.yml, docs/examples/CustomBundle/Resources/config/form_extensions/brand/edit.yml, docs/examples/CustomBundle/Resources/config/form_extensions/color/edit.yml, docs/examples/CustomBundle/Resources/config/form_extensions/fabric/create.yml, docs/examples/CustomBundle/Resources/config/form_extensions/fabric/edit.yml, docs/examples/CustomBundle/Resources/config/form_extensions/pictogram/edit.yml, docs/examples/CustomBundle/Resources/config/validation.yml, docs/examples/CustomBundle/Resources/translations/jsmessages.en.yml, spec/Pim/Bundle/CustomEntityBundle/Normalizer/CustomEntityNormalizerSpec.php
#142, #145 and #146 were submitted against the master branch, whereas they should have been against the 2.0 branch. This PR reports the fixes on the 2.0 branch.
The relevant commits were simply cherry-picked, in order to ease subsequent merge operations
=> Backport fixes into 2.0

CHANGELOG-2.0.md, Resources/public/js/field/custom-entity-select.js, Updater/Updater.php, spec/Pim/Bundle/CustomEntityBundle/Updater/UpdaterSpec.php
=> Allow removing an association between two custom entities

CHANGELOG-2.0.md, Updater/Updater.php, spec/Pim/Bundle/CustomEntityBundle/Updater/UpdaterSpec.php
=> Fix Updater when a CustomEntity has translations and is linked to another custom entity

.gitignore, .php_cs.php, CHANGELOG-2.0.md, Connector/Reader/Database/ReferenceDataReader.php, Entity/Repository/AttributeRepository.php, README.md, Tests/AbstractTestCase.php, Tests/AppKernelTest.php, Tests/AppKernelTestEe.php, Tests/Crud/AbstractCrudTestCase.php, Tests/Crud/CreateTest.php, Tests/Crud/DeleteTest.php, Tests/Crud/UpdateTest.php, Tests/Jobs/AbstractJobTestCase.php, Tests/Jobs/Export/CustomEntityExportTest.php, Tests/Jobs/Import/CustomEntityImportTest.php, Tests/Resources/data/brands.csv, Tests/Resources/data/colors.csv, Tests/Resources/data/fabrics.csv, Tests/Resources/parameters_test.yml, Tests/Resources/parameters_test_ee.yml, Tests/Resources/phpunit.xml
=> Integration tests

Normalizer/CustomEntityNormalizer.php, Resolver/FQCNResolver.php, Resources/config/serializer.yml, Resources/config/services.yml, Tests/Versioning/VersionableCustomEntityTest.php, Versioning/UpdateGuesser.php, docs/examples/CustomBundle/Entity/Color.php, docs/examples/CustomBundle/Normalizer/Standard/ColorNormalizer.php, docs/examples/CustomBundle/Resources/config/normalizers.yml, spec/Pim/Bundle/CustomEntityBundle/Normalizer/CustomEntityNormalizerSpec.php, spec/Pim/Bundle/CustomEntityBundle/Resolver/FQCNResolverSpec.php, spec/Pim/Bundle/CustomEntityBundle/Versioning/UpdateGuesserSpec.php
=> Enable entities versioning

Controller/AjaxOptionController.php, Controller/EnterpriseAjaxOptionController.php
=> Fix ReferenceData filter for ProductExportBuilder
